project:
  type: book

book:
  title: "Knowledge Map in TISE"
  author: "Armein Z. R. Langi"
  date: "16/12/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - km/km-01-basic.md 
    - km/km-02-bloom.md 
    - km/km-03-pudal.md 
    - km/km-04-abcd.md 
    - km/km-05-te.qmd 
    - km/km-06-energon.qmd  
    - km/km-08-pce.md
    - km/km-09-workflow.md 
    - km/km-10-meta.md
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



